[workspace]
authors = ["kaspermunch <kaspermunch@birc.au.dk>"]
channels = ["conda-forge", "munch-group"]
name = "munch-group-project"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
git = "*"
gh = "*"
pip = "*"
git-lfs = "*"
cryptography = "*"
jupyterlab = "*"
nodejs = "*"
seaborn = "*"
pytables = "*"
scipy = "*"
statsmodels = "*"
ipykernel = "*"
nbconvert = "*"

[tool.pixi.tasks.init]
args = [
  { "arg" = "new_name" }
]
cmd = "python ./scripts/rename.py {{new_name}} && gh repo set-default https://github.com/munch-group/{{new_name}}"
